# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/buildup/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: ec2-user
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 180
      runas: ec2-user